### ISSUE TITLE
Not Booting

### ISSUE THREAD

**Issue by Anonymous1808-tech** [AntarticShaurant/android_device_xiaomi_fire#1]
Hey I tested the twrp over a temporary boot. Unfortunately, it doesn't start at all and the device only boots into the system. I'll take a look at the coding if you don't mind

**Comment by AntarcticShaurant** [comment]
Oh hello, thank you for your report!

Yeah, this device doesn't allow temporary boot, you need to flash with
`fastboot flash boot twrp_boot.img`
then reboot to recovery, go in advanced, and flash to ramdisk(or something along the lines, i don't remember haha)

also, i don't think this recovery works, since i repacked it using AIK (Android Image Kitchen), without the --orig-size flag, so as you can see, it's a 42MB img, and i don't think fastboot will be able to flash it.
I'll release the right version asap.

**Comment by Anonymous1808-tech** [comment]
> Oh hello, thank you for your report!
> 
> Yeah, this device doesn't allow temporary boot, you need to flash with
> `fastboot flash boot twrp_boot.img`
> then reboot to recovery, go in advanced, and flash to ramdisk(or something along the lines, i don't remember haha)
> 
> also, i don't think this recovery works, since i repacked it using AIK (Android Image Kitchen), without the --orig-size flag, so as you can see, it's a 42MB img, and i don't think fastboot will be able to flash it.
> I'll release the right version asap.

hahaha no problem, I would like to lend a helping hand, but the situation is pretty critical right now. I currently only have a PC with less RAM than my toaster lol

**Comment by AntarcticShaurant** [comment]
Don't worry, i'm posting a temporary one right now, OTG works, but /data decryption doesn't, so you need to format data first

**Comment by AntarcticShaurant** [comment]
Posted :+1:

**Comment by Anonymous1808-tech** [comment]
> Posted 👍

hey twrp still doesn't work, I don't know if it's because I'm doing something wrong, but so far I have the same result as before. As before, I used fastboot boot because I wouldn't like to flash it at the beginning, after all, there is no real Redmi 12 (fire) community yet and the TWRP is a beta.

**Comment by AntarcticShaurant** [comment]
Yeah, as i said, it won't work if you boot it temporarily, and not only mine, but every recovery built for this device.
You need to flash it.
You may wait until i fix every major and medium bug, but it won't boot anyways.

(also, you need to wipe /data, only if the partition is already encrypted, so you might not need to do that)
